MathGamesApp/Controllers/ProblemController.cs
using MathGamesApp.Core.Contracts;
using MathGamesApp.Core.Models.Problem;
using MathGamesApp.Infrastructure.Data;
using MathGamesApp.Infrastructure.Data.Entities;
using Microsoft.AspNetCore.Mvc;

namespace MathGamesApp.Controllers
{
    public class ProblemController : Controller
    {
        private readonly IProblemService problemService;  

        public ProblemController(IProblemService _problemService)
        {
            problemService = _problemService;
        }


        public IActionResult AdditionProblems(int difficultyLevelId, int problemTypeId)
        {
            var problems = problemService.GenerateAdditionProblemsByLevel(difficultyLevelId, problemTypeId);

            var additionProblemViewModels = problems.Select(p => new AdditionProblemViewModel
            {
                Id = p.Id,
                Description = p.Description,
                UserAnswer = p.UserAnswer,
                Answer = p.Answer,
                DifficultyLevelId = difficultyLevelId,
                ProblemCategoryId = 1,
                ProblemTypeId = problemTypeId,
                IsCorrect = false,

            });

            return View(additionProblemViewModels);
        }

        public IActionResult DivisionProblems(int difficultyLevelId, int problemTypeId)
        {
            var problems = problemService.GenerateDivisionProblemsByLevel(difficultyLevelId, problemTypeId);

            var divisionProblemViewModels = problems.Select(p => new DivisionProblemViewModel
            {
                Id = p.Id,
                Description = p.Description,
                UserAnswer = p.UserAnswer,
                Answer = p.Answer,
                DifficultyLevelId = difficultyLevelId,
                ProblemCategoryId = 1,
                ProblemTypeId = problemTypeId,
                IsCorrect = false,

            });

            return View(divisionProblemViewModels);
        }

        public IActionResult MultiplicationProblems(int difficultyLevelId, int problemTypeId)
        {
            var problems = problemService.GenerateMultiplicationProblemsByLevel(difficultyLevelId, problemTypeId);

            var multiplicationProblemViewModels = problems.Select(p => new MultiplicationViewModel
            {
                Id = p.Id,
                Description = p.Description,
                UserAnswer = p.UserAnswer,
                Answer = p.Answer,
                DifficultyLevelId = difficultyLevelId,
                ProblemCategoryId = 1,
                ProblemTypeId = problemTypeId,
                IsCorrect = false,

            });

            return View(multiplicationProblemViewModels);
        }


        public IActionResult SubtractionProblems(int difficultyLevelId, int problemTypeId)
        {
            var subProblems = problemService.GenerateSubtractionProblemsByLevel(difficultyLevelId, problemTypeId);

            var subtractionProblemViewModels = subProblems.Select(sp => new SubtractionProblemViewModel
            {
                Id = sp.Id,
                Description = sp.Description,
                UserAnswer = sp.UserAnswer,
                Answer = sp.Answer,
                DifficultyLevelId = difficultyLevelId,
                ProblemCategoryId = 1,
                ProblemTypeId = problemTypeId, 
                IsCorrect = false,
            });

            return View(subtractionProblemViewModels);
        }

        [HttpPost]       
        public IActionResult CheckAnswersAddition(IEnumerable<AdditionProblemViewModel> problems)
        {
          
            bool allCorrect = problemService.CheckAdditionProblemAnswers(problems);

            if (allCorrect)
            {
                ViewData["Message"] = "Congratulations! All your answers are correct.";
            }
            else
            {

                ViewData["Message"] = "Sorry, some of your answers are incorrect. Please try again.";
            }

            return View("CheckAnswersAddition", problems);
        }

        [HttpPost]
        public IActionResult CheckAnswersMultiplication(IEnumerable<MultiplicationViewModel> problems)
        {

            bool allCorrect = problemService.CheckMultiplicationProblemAnswers(problems);

            if (allCorrect)
            {
                ViewData["Message"] = "Congratulations! All your answers are correct.";
            }
            else
            {

                ViewData["Message"] = "Sorry, some of your answers are incorrect. Please try again.";
            }

            return View("CheckAnswersMultiplication", problems);
        }


        [HttpPost]
        public IActionResult CheckAnswersSubtraction(IEnumerable<SubtractionProblemViewModel> subProblems)
        {

            bool allCorrect = problemService.CheckSubtractionProblemAnswers(subProblems);

            if (allCorrect)
            {
                ViewData["Message"] = "Congratulations! All your answers are correct.";
            }
            else
            {

                ViewData["Message"] = "Sorry, some of your answers are incorrect. Please try again.";
            }

            return View("CheckAnswersSubtraction", subProblems);
        }

        [HttpPost]
        public IActionResult CheckAnswersDivision(IEnumerable<DivisionProblemViewModel> divProblems)
        {

            bool allCorrect = problemService.CheckDivisionProblemAnswers(divProblems);

            if (allCorrect)
            {
                ViewData["Message"] = "Congratulations! All your answers are correct.";
            }
            else
            {

                ViewData["Message"] = "Sorry, some of your answers are incorrect. Please try again.";
            }

            return View("CheckAnswersDivision", divProblems);
        }


        public async Task<IActionResult> Description(int id)
        {
            
            var categoryModel = await problemService.GetCategoryDescriptionAsync(id);

            return View(categoryModel);
        }

        public async Task<IActionResult> Information(int id)
        {

            var typeModel = await problemService.GetTypeInformationAsync(id);

            return View(typeModel);
        }

        [HttpGet]
        [HttpPost]
        public async Task<IActionResult> GetProblemType(int categoryId)
        {
            var types = await problemService.GetAllTypesByCategoryAsync(categoryId);

            return View(types);
        }

        public IActionResult SubtractionDifficultyLevels()
        {
            var difficultyLevels = problemService.GetDifficultyLevelsByProblemType(2);

            var difficultyLevelViewModels = difficultyLevels.Select(d => new DifficultyLevelsViewModel
            {
                Id = d.Id,
                Name = d.Name,
                ProblemTypeId = 2
            });

            return View(difficultyLevelViewModels);
        }

        public IActionResult AdditionDifficultyLevels()
        {
            var difficultyLevels = problemService.GetDifficultyLevelsByProblemType(1);

            var difficultyLevelViewModels = difficultyLevels.Select(d => new DifficultyLevelsViewModel
            {
                Id = d.Id,
                Name = d.Name,
                ProblemTypeId = 1
            });

            return View(difficultyLevelViewModels);
        }

        public IActionResult MultiplicationDifficultyLevels()
        {
            var difficultyLevels = problemService.GetDifficultyLevelsByProblemType(3);

            var difficultyLevelViewModels = difficultyLevels.Select(d => new DifficultyLevelsViewModel
            {
                Id = d.Id,
                Name = d.Name,
                ProblemTypeId = 3
            });

            return View(difficultyLevelViewModels);
        }

        public IActionResult DivisionDifficultyLevels()
        {
            var difficultyLevels = problemService.GetDifficultyLevelsByProblemType(4);

            var difficultyLevelViewModels = difficultyLevels.Select(d => new DifficultyLevelsViewModel
            {
                Id = d.Id,
                Name = d.Name,
                ProblemTypeId = 4
            });

            return View(difficultyLevelViewModels);
        }

    }
}

MathGamesApp/Views/Problem/AdditionProblems.cshtml
@using MathGamesApp.Core.Models.Problem
@model IEnumerable<AdditionProblemViewModel>



<form method="post" action="@Url.Action("CheckAnswersAddition")">
  <table>
    <thead>
      <tr>
        <th>Problem</th>
        <th>Your Answer</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach (var problem in Model)
      {
        <tr>
          <td>@problem.Description</td>
          <td>
            <div class="input-group">
              <input type="hidden" name="problems[@problem.Id].Id" value="@problem.Id" />
              <input type="hidden" name="problems[@problem.Id].DifficultyLevelId" value="@problem.DifficultyLevelId" />
              <input type="hidden" name="problems[@problem.Id].ProblemCategoryId" value="@problem.ProblemCategoryId" />
              <input type="hidden" name="problems[@problem.Id].ProblemTypeId" value="@problem.ProblemTypeId" />
              <input type="number" class="form-control" name="problems[@problem.Id].UserAnswer" value="@problem.UserAnswer" />
              <input type="hidden" name="problems[@problem.Id].Answer" value="@problem.Answer" />
              <input type="hidden" name="problems[@problem.Id].Description" value="@problem.Description" />
              <input type="hidden" name="problems[@problem.Id].IsCorrect" value="@problem.IsCorrect" />
              <div class="input-group-append">
              </div>
            </div>
          </td>
          <td></td>
        </tr>
      }
    </tbody>
  </table>
  <button type="submit" class="btn btn-primary mt-3">Check Answers</button>
</form>

MathGamesApp/Views/Problem/CheckAnswers.cshtml
@using MathGamesApp.Core.Models.Problem
@model IEnumerable<AdditionProblemViewModel>


<h2>Check Addition Problem Answers</h2>

@if (Model.All(p => p.IsCorrect))
{
    <p class="success">Congratulations, you got all the answers correct!</p>
}
else
{
    <p class="error">Oops, you got some answers wrong. Here are the correct answers:</p>
    @foreach (var problem in Model)
    {
        <div class="problem @(problem.IsCorrect ? "correct" : "incorrect")">
            <p class="problem-description">@problem.Description</p>
            <div class="answer-section">
                <label>Your Answer:</label>
                <span>@problem.UserAnswer</span>
            </div>
            <div class="answer-section">
                <label>Correct Answer:</label>
                <span>@problem.Answer</span>
            </div>
            @Html.HiddenFor(model => problem.Id)
            @Html.HiddenFor(model => problem.DifficultyLevelId)
            @Html.HiddenFor(model => problem.ProblemCategoryId)
            @Html.HiddenFor(model => problem.ProblemTypeId)
        </div>
    }
}

<style>
    .success {
        color: green;
        font-weight: bold;
    }
    
    .error {
        color: red;
        font-weight: bold;
    }
    
    .problem {
        margin-bottom: 10px;
        padding: 10px;
        border: 1px solid black;
    }
    
    .problem .problem-description {
        font-weight: bold;
        margin-bottom: 5px;
    }
    
    .problem.correct {
        background-color: #cfc;
    }
    
    .problem.incorrect {
        background-color: #fcc;
    }
    
    .answer-section {
        display: inline-block;
        margin-right: 10px;
    }
</style>

MathGamesApp/Views/Problem/CheckAnswersAddition.cshtml
@using MathGamesApp.Core.Models.Problem
@model IEnumerable<AdditionProblemViewModel>


<h2>Check Addition Problem Answers</h2>

@if (Model.All(p => p.IsCorrect))
{
    <p class="success">Congratulations, you got all the answers correct!</p>
}
else
{
    <p class="error">Oops, you got some answers wrong. Here are the correct answers:</p>
    @foreach (var problem in Model)
    {
        <div class="problem @(problem.IsCorrect ? "correct" : "incorrect")">
            <p class="problem-description">@problem.Description</p>
            <div class="answer-section">
                <label>Your Answer:</label>
                <span>@problem.UserAnswer</span>
            </div>
            <div class="answer-section">
                <label>Correct Answer:</label>
                <span>@problem.Answer</span>
            </div>
            @Html.HiddenFor(model => problem.Id)
            @Html.HiddenFor(model => problem.DifficultyLevelId)
            @Html.HiddenFor(model => problem.ProblemCategoryId)
            @Html.HiddenFor(model => problem.ProblemTypeId)
        </div>
    }
}

<style>
    .success {
        color: green;
        font-weight: bold;
    }
    
    .error {
        color: red;
        font-weight: bold;
    }
    
    .problem {
        margin-bottom: 10px;
        padding: 10px;
        border: 1px solid black;
    }
    
    .problem .problem-description {
        font-weight: bold;
        margin-bottom: 5px;
    }
    
    .problem.correct {
        background-color: #cfc;
    }
    
    .problem.incorrect {
        background-color: #fcc;
    }
    
    .answer-section {
        display: inline-block;
        margin-right: 10px;
    }
</style>

MathGamesApp/Views/Problem/CheckAnswersDivision.cshtml
@using MathGamesApp.Core.Models.Problem
@model IEnumerable<DivisionProblemViewModel>


<h2>Check Division Problem Answers</h2>

@if (Model.All(p => p.IsCorrect))
{
    <p class="success">Congratulations, you got all the answers correct!</p>
}
else
{
    <p class="error">Oops, you got some answers wrong. Here are the correct answers:</p>
    @foreach (var problem in Model)
    {
        <div class="problem @(problem.IsCorrect ? "correct" : "incorrect")">
            <p class="problem-description">@problem.Description</p>
            <div class="answer-section">
                <label>Your Answer:</label>
                <span>@problem.UserAnswer</span>
            </div>
            <div class="answer-section">
                <label>Correct Answer:</label>
                <span>@problem.Answer</span>
            </div>
            @Html.HiddenFor(model => problem.Id)
            @Html.HiddenFor(model => problem.DifficultyLevelId)
            @Html.HiddenFor(model => problem.ProblemCategoryId)
            @Html.HiddenFor(model => problem.ProblemTypeId)
        </div>
    }
}

<style>
    .success {
        color: green;
        font-weight: bold;
    }
    
    .error {
        color: red;
        font-weight: bold;
    }
    
    .problem {
        margin-bottom: 10px;
        padding: 10px;
        border: 1px solid black;
    }
    
    .problem .problem-description {
        font-weight: bold;
        margin-bottom: 5px;
    }
    
    .problem.correct {
        background-color: #cfc;
    }
    
    .problem.incorrect {
        background-color: #fcc;
    }
    
    .answer-section {
        display: inline-block;
        margin-right: 10px;
    }
</style>

MathGamesApp/Views/Problem/CheckAnswersMultiplication.cshtml
@using MathGamesApp.Core.Models.Problem
@model IEnumerable<MultiplicationViewModel>


<h2>Check Multiplication Problem Answers</h2>

@if (Model.All(p => p.IsCorrect))
{
    <p class="success">Congratulations, you got all the answers correct!</p>
}
else
{
    <p class="error">Oops, you got some answers wrong. Here are the correct answers:</p>
    @foreach (var problem in Model)
    {
        <div class="problem @(problem.IsCorrect ? "correct" : "incorrect")">
            <p class="problem-description">@problem.Description</p>
            <div class="answer-section">
                <label>Your Answer:</label>
                <span>@problem.UserAnswer</span>
            </div>
            <div class="answer-section">
                <label>Correct Answer:</label>
                <span>@problem.Answer</span>
            </div>
            @Html.HiddenFor(model => problem.Id)
            @Html.HiddenFor(model => problem.DifficultyLevelId)
            @Html.HiddenFor(model => problem.ProblemCategoryId)
            @Html.HiddenFor(model => problem.ProblemTypeId)
        </div>
    }
}

<style>
    .success {
        color: green;
        font-weight: bold;
    }
    
    .error {
        color: red;
        font-weight: bold;
    }
    
    .problem {
        margin-bottom: 10px;
        padding: 10px;
        border: 1px solid black;
    }
    
    .problem .problem-description {
        font-weight: bold;
        margin-bottom: 5px;
    }
    
    .problem.correct {
        background-color: #cfc;
    }
    
    .problem.incorrect {
        background-color: #fcc;
    }
    
    .answer-section {
        display: inline-block;
        margin-right: 10px;
    }
</style>

MathGamesApp/Views/Problem/CheckAnswersSubtraction.cshtml
@using MathGamesApp.Core.Models.Problem
@model IEnumerable<SubtractionProblemViewModel>


<h2>Check Subtraction Problem Answers</h2>

@if (Model.All(p => p.IsCorrect))
{
    <p class="success">Congratulations, you got all the answers correct!</p>
}
else
{
    <p class="error">Oops, you got some answers wrong. Here are the correct answers:</p>
    @foreach (var subProblem in Model)
    {
        <div class="problem @(subProblem.IsCorrect ? "correct" : "incorrect")">
            <p class="problem-description">@subProblem.Description</p>
            <div class="answer-section">
                <label>Your Answer:</label>
                <span>@subProblem.UserAnswer</span>
            </div>
            <div class="answer-section">
                <label>Correct Answer:</label>
                <span>@subProblem.Answer</span>
            </div>
            @Html.HiddenFor(model => subProblem.Id)
            @Html.HiddenFor(model => subProblem.DifficultyLevelId)
            @Html.HiddenFor(model => subProblem.ProblemCategoryId)
            @Html.HiddenFor(model => subProblem.ProblemTypeId)
        </div>
    }
}

<style>
    .success {
        color: green;
        font-weight: bold;
    }
    
    .error {
        color: red;
        font-weight: bold;
    }
    
    .problem {
        margin-bottom: 10px;
        padding: 10px;
        border: 1px solid black;
    }
    
    .problem .problem-description {
        font-weight: bold;
        margin-bottom: 5px;
    }
    
    .problem.correct {
        background-color: #cfc;
    }
    
    .problem.incorrect {
        background-color: #fcc;
    }
    
    .answer-section {
        display: inline-block;
        margin-right: 10px;
    }
</style>

MathGamesApp/Views/Problem/Description.cshtml
@using MathGamesApp.Core.Models
@model ProblemCategoryViewModel

@{
    ViewData["Title"] = "Description";
}

<div class="col-md-3 mb-4">
             <div class="category-card" onclick="location.href='@Url.Action("GetProblemType", "Problem", new { categoryId = Model.Id })';" style="cursor: pointer;">
                <div class="category-card-header">
                    <h5 class="category-card-name">@Model.Name</h5>
                </div>
                <div class="category-card-img">
                    <img src="@Model.ImageUrl" alt="Category Image" />
                </div>              
                <div class="category-card-description">
                    <p>@Model.Description</p>
                </div>
            </div>
        </div>


        <style>
    .category-card {
        border-radius: 5px;
        box-shadow: 0px 1px 4px rgba(0, 0, 0, 0.2);
        overflow: hidden;
        transition: box-shadow 0.2s ease-in-out;
    }
    .category-card:hover {
        box-shadow: 0px 1px 8px rgba(0, 0, 0, 0.3);
    }
    .category-card-img {
        height: 200px;
        overflow: hidden;
    }
    .category-card-img img {
        width: 100%;
    }
    .category-card-header {
        padding: 20px;
    }
    .category-card-name {
        margin-bottom: 0;
    }
    
</style>

MathGamesApp/Views/Problem/DivisionDifficultyLevels.cshtml
@using MathGamesApp.Core.Models.Problem

@model IEnumerable<DifficultyLevelsViewModel>

<h1>Choose a difficulty level for division problems</h1>

@foreach(var level in Model)
{
    <a asp-controller="Problem" asp-action="DivisionProblems" asp-route-difficultyLevelId="@level.Id">
        <input type="submit" value="@level.Name" />
    </a>
}

MathGamesApp/Views/Problem/DivisionProblems.cshtml
@using MathGamesApp.Core.Models.Problem
@model IEnumerable<DivisionProblemViewModel>



<form method="post" action="@Url.Action("CheckAnswersDivision")">
  <table>
    <thead>
      <tr>
        <th>Problem</th>
        <th>Your Answer</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach (var problem in Model)
      {
        <tr>
          <td>@problem.Description</td>
          <td>
            <div class="input-group">
              <input type="hidden" name="problems[@problem.Id].Id" value="@problem.Id" />
              <input type="hidden" name="problems[@problem.Id].DifficultyLevelId" value="@problem.DifficultyLevelId" />
              <input type="hidden" name="problems[@problem.Id].ProblemCategoryId" value="@problem.ProblemCategoryId" />
              <input type="hidden" name="problems[@problem.Id].ProblemTypeId" value="@problem.ProblemTypeId" />
              <input type="number" class="form-control" name="problems[@problem.Id].UserAnswer" value="@problem.UserAnswer" />
              <input type="hidden" name="problems[@problem.Id].Answer" value="@problem.Answer" />
              <input type="hidden" name="problems[@problem.Id].Description" value="@problem.Description" />
              <input type="hidden" name="problems[@problem.Id].IsCorrect" value="@problem.IsCorrect" />
              <div class="input-group-append">
              </div>
            </div>
          </td>
          <td></td>
        </tr>
      }
    </tbody>
  </table>
  <button type="submit" class="btn btn-primary mt-3">Check Answers</button>
</form>

MathGamesApp/Views/Problem/GetProblemType.cshtml
@using MathGamesApp.Core.Models
@model IEnumerable<ProblemTypeViewModel>

@{
    ViewData["Title"] = "Problem Type";
}

<div class="row">
    @foreach (var type in Model)
    {
        <div class="col-md-3 mb-4">
           <div class="type-card" onclick="location.href='@Url.Action(type.Id == 1 ? "AdditionDifficultyLevels" : 
                                                                    (type.Id == 2 ? "SubtractionDifficultyLevels" : 
                                                                    (type.Id == 3 ? "MultiplicationDifficultyLevels" : "DivisionDifficultyLevels")), "Problem", 
                                                                    new { typeId = type.Id })';" style="cursor: pointer;">
                <div class="type-card-header">          
                    <h5 class="type-card-name">@type.Name</h5>
                    <form class="type-card-description" asp-controller="Problem" asp-action="Information" asp-route-id="@type.Id">
                        <input type="submit" value="?"/>
                    </form>
                </div>
                <div class="type-card-img">
                    <img src="@type.ImageUrl" alt="Type Image" />
                </div>
            </div>
        </div>
    }
</div>


@*Should move the css somewhere else*@
<style>
    .type-card {
        border-radius: 5px;
        box-shadow: 0px 1px 4px rgba(0, 0, 0, 0.2);
        overflow: hidden;
        transition: box-shadow 0.2s ease-in-out;
    }
    .type-card:hover {
        box-shadow: 0px 1px 8px rgba(0, 0, 0, 0.3);
    }
    .type-card-img {
        height: 200px;
        overflow: hidden;
    }
    .type-card-img img {
        width: 100%;
    }
    .type-card-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 20px;
    }
    .type-card-name {
        margin-bottom: 0;
    }
    
</style>

MathGamesApp/Views/Problem/Information.cshtml
@using MathGamesApp.Core.Models
@model ProblemTypeViewModel

@{
    ViewData["Title"] = "Home Page";
}
    <div class="col-md-3 mb-4">
            <div class="type-card">
                <div class="type-card-header">
                    <h5 class="type-card-name">@Model.Name</h5>                      
                </div>
                <div class="type-card-img">
                    <img src="@Model.ImageUrl" alt="Category Image" />
                </div>  
                <div class="type-card-information">
                    <p>@Model.Instruction</p>
                </div>
            </div>
        </div>
  

@*Should move the css somewhere else*@
<style>
    .type-card {
        border-radius: 5px;
        box-shadow: 0px 1px 4px rgba(0, 0, 0, 0.2);
        overflow: hidden;
        transition: box-shadow 0.2s ease-in-out;
    }
    .type-card:hover {
        box-shadow: 0px 1px 8px rgba(0, 0, 0, 0.3);
    }
    .type-card-img {
        height: 200px;
        overflow: hidden;
    }
    .type-card-img img {
        width: 100%;
    }
    .type-card-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 20px;
    }
    .type-card-name {
        margin-bottom: 0;
    }
    
</style>

MathGamesApp/Views/Problem/MultiplicationProblems.cshtml
@using MathGamesApp.Core.Models.Problem
@model IEnumerable<MultiplicationViewModel>



<form method="post" action="@Url.Action("CheckAnswersMultiplication")">
  <table>
    <thead>
      <tr>
        <th>Problem</th>
        <th>Your Answer</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach (var problem in Model)
      {
        <tr>
          <td>@problem.Description</td>
          <td>
            <div class="input-group">
              <input type="hidden" name="problems[@problem.Id].Id" value="@problem.Id" />
              <input type="hidden" name="problems[@problem.Id].DifficultyLevelId" value="@problem.DifficultyLevelId" />
              <input type="hidden" name="problems[@problem.Id].ProblemCategoryId" value="@problem.ProblemCategoryId" />
              <input type="hidden" name="problems[@problem.Id].ProblemTypeId" value="@problem.ProblemTypeId" />
              <input type="number" class="form-control" name="problems[@problem.Id].UserAnswer" value="@problem.UserAnswer" />
              <input type="hidden" name="problems[@problem.Id].Answer" value="@problem.Answer" />
              <input type="hidden" name="problems[@problem.Id].Description" value="@problem.Description" />
              <input type="hidden" name="problems[@problem.Id].IsCorrect" value="@problem.IsCorrect" />
              <div class="input-group-append">
              </div>
            </div>
          </td>
          <td></td>
        </tr>
      }
    </tbody>
  </table>
  <button type="submit" class="btn btn-primary mt-3">Check Answers</button>
</form>

MathGamesApp/Views/Problem/SubtractionDifficultyLevels.cshtml
@using MathGamesApp.Core.Models.Problem

@model IEnumerable<DifficultyLevelsViewModel>

<h1>Choose a difficulty level for subtraction problems</h1>

@foreach(var level in Model)
{
    <a asp-controller="Problem" asp-action="SubtractionProblems" asp-route-difficultyLevelId="@level.Id">
        <input type="submit" value="@level.Name" />
    </a>
}

MathGamesApp/Views/Problem/SubtractionProblems.cshtml
@using MathGamesApp.Core.Models.Problem
@model IEnumerable<SubtractionProblemViewModel>



<form method="post" action="@Url.Action("CheckAnswersSubtraction")">
  <table>
    <thead>
      <tr>
        <th>Problem</th>
        <th>Your Answer</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach (var subProblem in Model)
      {
        <tr>
          <td>@subProblem.Description</td>
          <td>
            <div class="input-group">
              <input type="hidden" name="problems[@subProblem.Id].Id" value="@subProblem.Id" />
              <input type="hidden" name="problems[@subProblem.Id].DifficultyLevelId" value="@subProblem.DifficultyLevelId" />
              <input type="hidden" name="problems[@subProblem.Id].ProblemCategoryId" value="@subProblem.ProblemCategoryId" />
              <input type="hidden" name="problems[@subProblem.Id].ProblemTypeId" value="@subProblem.ProblemTypeId" />
              <input type="number" class="form-control" name="problems[@subProblem.Id].UserAnswer" value="@subProblem.UserAnswer" />
              <input type="hidden" name="problems[@subProblem.Id].Answer" value="@subProblem.Answer" />
              <input type="hidden" name="problems[@subProblem.Id].Description" value="@subProblem.Description" />
              <input type="hidden" name="problems[@subProblem.Id].IsCorrect" value="@subProblem.IsCorrect" />
              <div class="input-group-append">
              </div>
            </div>
          </td>
          <td></td>
        </tr>
      }
    </tbody>
  </table>
  <button type="submit" class="btn btn-primary mt-3">Check Answers</button>
</form>